c-call-lua:
	gcc lua-interpretor.c -I/Users/mengxiang/Documents/XIA/DDoS-system/Grantor/lua-5.1.5/include -L/Users/mengxiang/Documents/XIA/DDoS-system/Grantor/lua-5.1.5/lib -llua -lm
lua-dir:
	gcc lua-call-c-dir.c -I/Users/mengxiang/Documents/XIA/DDoS-system/Grantor/lua-5.1.5/include -L/Users/mengxiang/Documents/XIA/DDoS-system/Grantor/lua-5.1.5/lib -llua -lm

